<?php
echo "<html>\n";
echo "   <head>\n";
echo "       <title>NGA2021火箭</title>\n";
echo "       <meta charset=\"utf-8\">\n";
echo "       <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
echo "       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\n";
echo "       <script src=\"https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\"></script>\n";
echo "   </head>\n";
echo "   <body>\n";
echo "	<p>点击图片试试？或者刷新页面？</p>\n";
echo "       <img id=\"rand\" src=\"./api.php\" onclick=\"imgKick()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick(){\n";
echo "               var url = \"./api.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand1\" src=\"./api1.php\" onclick=\"imgKick1()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick1(){\n";
echo "               var url = \"./api1.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand1').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand2\" src=\"./api2.php\" onclick=\"imgKick2()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick2(){\n";
echo "               var url = \"./api2.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand2').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand3\" src=\"./api3.php\" onclick=\"imgKick3()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick3(){\n";
echo "               var url = \"./api3.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand3').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand4\" src=\"./api4.php\" onclick=\"imgKick4()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick4(){\n";
echo "               var url = \"./api4.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand4').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand5\" src=\"./api5.php\" onclick=\"imgKick5()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick5(){\n";
echo "               var url = \"./api5.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand5').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand6\" src=\"./api6.php\" onclick=\"imgKick6()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick6(){\n";
echo "               var url = \"./api6.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand6').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand7\" src=\"./api7.php\" onclick=\"imgKick7()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick7(){\n";
echo "               var url = \"./api7.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand7').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand8\" src=\"./api8.php\" onclick=\"imgKick8()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick8(){\n";
echo "               var url = \"./api8.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand8').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand9\" src=\"./api9.php\" onclick=\"imgKick9()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick9(){\n";
echo "               var url = \"./api9.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand9').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "       <br>\n";
echo "	<br>\n";
echo "       <img id=\"rand10\" src=\"./api10.php\" onclick=\"imgKick10()\" style=\"width:100%\"/>\n";
echo "       <script>\n";
echo "           function imgKick10(){\n";
echo "               var url = \"./api10.php?v=\"+Math.round(Math.random()*100);\n";
echo "               $('#rand10').attr('src',url);\n";
echo "           }\n";
echo "       </script>\n";
echo "   </body>\n";
echo "</html>\n";
?>